services:
  frontend:
    # tty: true
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-build  # Specifies which stage to build up to
    ports:
      - "5173:5173"  # Adjust if your frontend server uses a different port
    # volumes:
    #   - ./frontend/src:/usr/src/frontend/src  # For live reloading in development
    depends_on:
      - backend
    command: ["npx", "vite", "--host", "0.0.0.0", "--port", "5173"]

  backend:
    # tty: true
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-build 
    ports:
      - "5000:5000"  # Adjust if your backend server uses a different port
    # volumes:
    #   - ./backend/src:/usr/src/backend/src  # For live reloading in development
    command: ["npm", "run", "start"]
