# Start from a node base image
FROM node:latest

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY backend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend source code
COPY backend/ .

# Expose the port the app runs on
EXPOSE 5000

# Start the application
CMD ["npm", "start"]
